// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYNCIr9bNOOJ4S5m0lcQeIfbqGXRUF9aw',
    appId: '1:599399866992:web:6843eddf430a0d81ca0ab5',
    messagingSenderId: '599399866992',
    projectId: 'rozgarlink-b8525',
    authDomain: 'rozgarlink-b8525.firebaseapp.com',
    storageBucket: 'rozgarlink-b8525.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHggLkPYNPLIBLuvluAg0b6wYDSDNpTA0',
    appId: '1:599399866992:android:301a598b3167834dca0ab5',
    messagingSenderId: '599399866992',
    projectId: 'rozgarlink-b8525',
    storageBucket: 'rozgarlink-b8525.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1GuvJx1YoXBf2iMGFMadXYMo2Fwf7jS0',
    appId: '1:599399866992:ios:24114dec094bf892ca0ab5',
    messagingSenderId: '599399866992',
    projectId: 'rozgarlink-b8525',
    storageBucket: 'rozgarlink-b8525.firebasestorage.app',
    iosBundleId: 'com.example.rozgarLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1GuvJx1YoXBf2iMGFMadXYMo2Fwf7jS0',
    appId: '1:599399866992:ios:24114dec094bf892ca0ab5',
    messagingSenderId: '599399866992',
    projectId: 'rozgarlink-b8525',
    storageBucket: 'rozgarlink-b8525.firebasestorage.app',
    iosBundleId: 'com.example.rozgarLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    // apiKey: 'AIzaSyCYNCIr9bNOOJ4S5m0lcQeIfbqGXRUF9aw',
    apiKey: "AIzaSyCYH7mKP_UR3eHBLjLHcM-KVpr6xeKBXLc",
    // appId: '1:599399866992:web:28f0f0ec8a6e410cca0ab5',
    appId: "1:1075566240565:web:b3765dbcc2da66a4fb627c",
    messagingSenderId: '599399866992',
    projectId: 'rozgarlink-b8525',
    authDomain: 'rozgarlink-b8525.firebaseapp.com',
    storageBucket: 'rozgarlink-b8525.firebasestorage.app',
  );
}
